baseURL = 'https://gabrielabevenuto.com'
languageCode = 'pt_BR'
title = 'Gabriela Bevenuto'
profileImage = "images/profile.jpg"
email = "her.email@example.com"

[[params.section]]
name = "Sobre mim"
url = '/gabi'

[[params.section]]
name = 'Meu livro'
url = '/livros'

[[params.section]]
name = 'Recursos'
url = '/recursos'



[[params.socialLinks]]
name = "YouTube"
url = "https://www.youtube.com/@gabrielabevenuto/"

[[params.socialLinks]]
name = "Instagram"
url = "https://www.instagram.com/gabriela.bevenuto/"

[[params.socialLinks]]
name = "E-mail"
url = ""

[[params.membros]]
name = "Apoia-se"
url = ""

